### ISSUE TITLE
Small Design Tweaks

### ISSUE THREAD

**Issue by mikelmaron** [wearemarchon/strikewithus#5]
* [x]  When click on an event link, load in a new window
* [x] The map markers have a pixelated edge. Make these sharper
* [x] add ActionNetwork referral code. For example, referral=stop-the-money-pipeline. When present, append to the the event links in the popup, according to this example https://actionnetwork.org/events/chico-ca-joins-earth-day-global-climate-strike-actions-april-22-24?source=stop-the-money-pipeline&referrer=group-stop-the-money-pipeline
* [x] add black border on all sides of day buttons

**Comment by meganrm** [comment]
I think there should be a reset button. like 'ALL' that takes you back to the default view. Also clearing the search should do that. 
I think the colors of the markers for the different days should be indicated on the day buttons as a legend. Maybe the text 'Day 1' or the border could be the same color as the marker.

**Comment by mikelmaron** [comment]
@meganrm makes sense. do you want to take a try at what this looks like? or ask wearemarchon's designer for a mockup?

**Comment by mikelmaron** [comment]
Thanks for https://github.com/wearemarchon/strikewithus/pull/9 @meganrm. I've marked off two of the items here (new window and border). Remaining is pixelated marker and ref code

**Comment by meganrm** [comment]
Hey, I'm really sorry I didn't say something before, but since some of these things were pretty fast to work on, I didn't mind adding them in, but I think they're all technically outside the scope of what I was brought on to work on. The easy fix for the pixelated images is to use svgs (either in adding them to the map style or loading on the front end) but I don't have time to do that by the current deadline, I also thought you said you had someone that was going to fix this. I might be able to do the ref code since it's probably a one liner, but I am focusing on getting the filtering fixed and looking good

**Comment by mikelmaron** [comment]
pixelated image fixed!
